# Generated by Django 5.1.1 on 2024-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('category', models.CharField(blank=True, choices=[('EXT', 'Extra'), ('PRI', 'Primeira'), ('SEG', 'Segunda'), ('TER', 'Terceira')], max_length=3, null=True)),
                ('fresh_fruit', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3)),
                ('quant', models.IntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
