# Generated by Django 5.1.1 on 2024-09-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='fresh_fruit',
            field=models.BooleanField(default=True),
        ),
    ]
