# Generated by Django 5.1.1 on 2024-09-16 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fruits', '0002_alter_fruit_fresh_fruit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(choices=[(0.0, '0%'), (0.05, '5%'), (0.1, '10%'), (0.15, '15%'), (0.2, '20%'), (0.25, '25%')], decimal_places=2, default=0.0, max_digits=4)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_time', models.DateTimeField(auto_now_add=True)),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.fruit')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
